### ISSUE TITLE
When using suppress-chunks-webpack-plugin having this error, how to overcome?

### ISSUE THREAD

**Issue by Rohitgowda** [alxlu/suppress-chunks-webpack-plugin#1]
```
`  new SuppressChunksPlugin([
        ^
TypeError: SuppressChunksPlugin is not a constructor
    at Object.<anonymous> (/Users/rohit/WebstormProjects/myProjectStructure/webpack.config.js:80:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:97:18)
    at /usr/local/lib/node_modules/webpack/bin/convert-argv.js:104:17`
```

**Comment by Rohitgowda** [comment]
I got it cleared, thank you very much.

**Comment by diegolaciar** [comment]
I have the same error.

new SuppressChunksPlugin(["main"]),
                
TypeError: SuppressChunksPlugin is not a constructor

**Comment by oodzchen** [comment]
@Rohitgowda How do you fix that? I got the same error

**Comment by Rohitgowda** [comment]
@diegolaciar , @oodzchen 
The suppress-chunks-webpack-plugin uses ES modules and only has a default export (see also the transpiled source unpkg - suppress-chunks-webpack-plugin).To use it with Node's require you need to access the default property.
**var SuppressChunksPlugin = require('suppress-chunks-webpack-plugin').default;**
